//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Core.EntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OnBoadTaskEntities : DbContext
    {
        public OnBoadTaskEntities()
            : base("name=OnBoadTaskEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserDetail> UserDetails { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
        public virtual DbSet<Desigation> Desigations { get; set; }
    
        public virtual ObjectResult<GetGalleryItem_Result> GetGalleryItem(Nullable<long> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetGalleryItem_Result>("GetGalleryItem", idParameter);
        }
    
        public virtual int SaveUserDetails(Nullable<int> id, Nullable<int> curCountry, Nullable<int> curState, Nullable<int> curCity, string curZipCode, string curAddress1, string curAddress2, string profileUrl, Nullable<long> userId, Nullable<bool> isDefault)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var curCountryParameter = curCountry.HasValue ?
                new ObjectParameter("CurCountry", curCountry) :
                new ObjectParameter("CurCountry", typeof(int));
    
            var curStateParameter = curState.HasValue ?
                new ObjectParameter("CurState", curState) :
                new ObjectParameter("CurState", typeof(int));
    
            var curCityParameter = curCity.HasValue ?
                new ObjectParameter("CurCity", curCity) :
                new ObjectParameter("CurCity", typeof(int));
    
            var curZipCodeParameter = curZipCode != null ?
                new ObjectParameter("CurZipCode", curZipCode) :
                new ObjectParameter("CurZipCode", typeof(string));
    
            var curAddress1Parameter = curAddress1 != null ?
                new ObjectParameter("CurAddress1", curAddress1) :
                new ObjectParameter("CurAddress1", typeof(string));
    
            var curAddress2Parameter = curAddress2 != null ?
                new ObjectParameter("CurAddress2", curAddress2) :
                new ObjectParameter("CurAddress2", typeof(string));
    
            var profileUrlParameter = profileUrl != null ?
                new ObjectParameter("ProfileUrl", profileUrl) :
                new ObjectParameter("ProfileUrl", typeof(string));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(long));
    
            var isDefaultParameter = isDefault.HasValue ?
                new ObjectParameter("IsDefault", isDefault) :
                new ObjectParameter("IsDefault", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SaveUserDetails", idParameter, curCountryParameter, curStateParameter, curCityParameter, curZipCodeParameter, curAddress1Parameter, curAddress2Parameter, profileUrlParameter, userIdParameter, isDefaultParameter);
        }
    
        public virtual int SaveUserDetails1(Nullable<int> id, Nullable<int> curCountry, Nullable<int> curState, Nullable<int> curCity, string curZipCode, string curAddress1, string curAddress2, string profileUrl, Nullable<long> userId, Nullable<bool> isDefault)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var curCountryParameter = curCountry.HasValue ?
                new ObjectParameter("CurCountry", curCountry) :
                new ObjectParameter("CurCountry", typeof(int));
    
            var curStateParameter = curState.HasValue ?
                new ObjectParameter("CurState", curState) :
                new ObjectParameter("CurState", typeof(int));
    
            var curCityParameter = curCity.HasValue ?
                new ObjectParameter("CurCity", curCity) :
                new ObjectParameter("CurCity", typeof(int));
    
            var curZipCodeParameter = curZipCode != null ?
                new ObjectParameter("CurZipCode", curZipCode) :
                new ObjectParameter("CurZipCode", typeof(string));
    
            var curAddress1Parameter = curAddress1 != null ?
                new ObjectParameter("CurAddress1", curAddress1) :
                new ObjectParameter("CurAddress1", typeof(string));
    
            var curAddress2Parameter = curAddress2 != null ?
                new ObjectParameter("CurAddress2", curAddress2) :
                new ObjectParameter("CurAddress2", typeof(string));
    
            var profileUrlParameter = profileUrl != null ?
                new ObjectParameter("ProfileUrl", profileUrl) :
                new ObjectParameter("ProfileUrl", typeof(string));
    
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(long));
    
            var isDefaultParameter = isDefault.HasValue ?
                new ObjectParameter("IsDefault", isDefault) :
                new ObjectParameter("IsDefault", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SaveUserDetails1", idParameter, curCountryParameter, curStateParameter, curCityParameter, curZipCodeParameter, curAddress1Parameter, curAddress2Parameter, profileUrlParameter, userIdParameter, isDefaultParameter);
        }
    
        public virtual ObjectResult<GetPlacedOrders_Result> GetPlacedOrders(Nullable<long> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPlacedOrders_Result>("GetPlacedOrders", idParameter);
        }
    
        public virtual ObjectResult<GetOrdersByShippingId_Result> GetOrdersByShippingId(Nullable<long> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOrdersByShippingId_Result>("GetOrdersByShippingId", idParameter);
        }
    
        public virtual ObjectResult<GetPaidOrderDetail_Result> GetPaidOrderDetail()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPaidOrderDetail_Result>("GetPaidOrderDetail");
        }
    }
}
