//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Core.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<int> CurCountry { get; set; }
        public Nullable<int> CurState { get; set; }
        public Nullable<int> CurCity { get; set; }
        public string CurZipCode { get; set; }
        public string CurAddress1 { get; set; }
        public string CurAddress2 { get; set; }
        public string ProfileUrl { get; set; }
        public long UserId { get; set; }
        public bool IsDefault { get; set; }
    
        public virtual User User { get; set; }
    }
}
